# SonarQube Project Properties
sonar.projectKey=sbvia-backend
sonar.projectName=SBVIA Backend
sonar.projectVersion=0.9.0-rc

# Set modules
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java

# Encoding
sonar.sourceEncoding=UTF-8

# Java binaries and coverage reports
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
