CREATE TABLE public.respaldo (
    id_respaldo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP,
    tamanio_bytes BIGINT,
    detalles TEXT
);

COMMENT ON TABLE public.respaldo IS 'Tabla para registrar el historial de respaldos (manuales y programados).';

ALTER TABLE public.respaldo
    ADD CONSTRAINT chk_respaldo_tipo CHECK (tipo IN ('MANUAL', 'PROGRAMADO'));

ALTER TABLE public.respaldo
    ADD CONSTRAINT chk_respaldo_estado CHECK (estado IN ('EN_PROGRESO', 'COMPLETADO', 'FALLIDO'));
