CREATE TABLE "Rol" ( 
  "id_Rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar NOT NULL 
); 

CREATE TABLE "Usuario" ( 
  "id_Usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "apellido" varchar NOT NULL, 
  "email" varchar NOT NULL UNIQUE,
  "password_hash" varchar NOT NULL,
  "telefono" varchar,
  "tipo_licencia" varchar,
  "fecha_registro" date NOT NULL DEFAULT CURRENT_DATE, 
  "estado" varchar NOT NULL, 
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamptz NOT NULL DEFAULT NOW(),
  "actualizado_en" timestamptz NOT NULL DEFAULT NOW(),
  "id_Rol" integer NOT NULL 
); 

CREATE TABLE "Escenario" ( 
  "id_Escenario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar, 
  "tipo_via" varchar NOT NULL, 
  "nivel_dificultad" integer NOT NULL, 
  "clima" varchar NOT NULL, 
  "densidad_trafico" varchar NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamptz NOT NULL DEFAULT NOW(),
  "actualizado_en" timestamptz NOT NULL DEFAULT NOW()
); 

CREATE TABLE "Simulacion" ( 
  "id_Simulacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "fecha_inicio" date NOT NULL, 
  "fecha_fin" date NOT NULL, 
  "estado" varchar NOT NULL, 
  "puntaje_final" decimal NOT NULL, 
  "id_Usuario" integer NOT NULL, 
  "id_Escenario" integer NOT NULL 
); 

CREATE TABLE "EventoVial" ( 
  "id_EventoVial" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar, 
  "tipo_evento" varchar NOT NULL, 
  "nivel_riesgo" integer NOT NULL, 
  "id_Simulacion" integer NOT NULL 
); 

CREATE TABLE "Decision" ( 
  "id_Decision" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "accion_realizada" varchar NOT NULL, 
  "resultado" varchar NOT NULL, 
  "momento" date NOT NULL, 
  "id_Simulacion" integer NOT NULL 
); 

CREATE TABLE "ReglaTransito" ( 
  "id_ReglaTransito" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar, 
  "categoria" varchar NOT NULL, 
  "id_Escenario" integer NOT NULL 
); 

CREATE TABLE "Infraccion" ( 
  "id_Infraccion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar, 
  "gravedad" varchar NOT NULL, 
  "penalizacion" decimal NOT NULL, 
  "id_Simulacion" integer NOT NULL 
); 

CREATE TABLE "ComportamientoVial" ( 
  "id_ComportamientoVial" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "clasificacion" varchar NOT NULL, 
  "nivel_riesgo" integer NOT NULL, 
  "observaciones" varchar, 
  "id_Decision" integer NOT NULL 
); 

CREATE TABLE "Retroalimentacion" ( 
  "id_Retroalimentacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "comentario" varchar NOT NULL, 
  "recomendacion" varchar, 
  "fecha_generacion" date NOT NULL, 
  "id_Simulacion" integer NOT NULL, 
  "id_ComportamientoVial" integer NOT NULL 
); 

CREATE TABLE "MetricaDesempeno" ( 
  "id_MetricaDesempeno" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "puntaje" decimal NOT NULL, 
  "tiempo_reaccion" decimal NOT NULL, 
  "errores" integer NOT NULL, 
  "aciertos" integer NOT NULL, 
  "nivel_desempeno" varchar NOT NULL, 
  "id_Simulacion" integer NOT NULL 
); 

CREATE TABLE "Reporte" ( 
  "id_Reporte" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "tipo_reporte" varchar NOT NULL, 
  "fecha_generacion" date NOT NULL, 
  "observaciones" varchar NOT NULL, 
  "id_Simulacion" integer NOT NULL 
); 

CREATE TABLE "Recompensa" ( 
  "id_Recompensa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  "nombre" varchar NOT NULL, 
  "descripcion" varchar NOT NULL, 
  "nivel" integer NOT NULL, 
  "puntos_requeridos" integer NOT NULL, 
  "id_Usuario" integer NOT NULL 
); 

ALTER TABLE "Simulacion" ADD CONSTRAINT "fk_Simulacion_id_Escenario_Escenario" FOREIGN KEY ("id_Escenario") REFERENCES "Escenario" ("id_Escenario") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Usuario" ADD CONSTRAINT "fk_Usuario_id_Rol_Rol" FOREIGN KEY ("id_Rol") REFERENCES "Rol" ("id_Rol") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Simulacion" ADD CONSTRAINT "fk_Simulacion_id_Usuario_Usuario" FOREIGN KEY ("id_Usuario") REFERENCES "Usuario" ("id_Usuario") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Decision" ADD CONSTRAINT "fk_Decision_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "ComportamientoVial" ADD CONSTRAINT "fk_ComportamientoVial_id_Decision_Decision" FOREIGN KEY ("id_Decision") REFERENCES "Decision" ("id_Decision") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Retroalimentacion" ADD CONSTRAINT "fk_Retroalimentacion_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Retroalimentacion" ADD CONSTRAINT "fk_Retroalimentacion_id_ComportamientoVial_ComportamientoVial" FOREIGN KEY ("id_ComportamientoVial") REFERENCES "ComportamientoVial" ("id_ComportamientoVial") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "MetricaDesempeno" ADD CONSTRAINT "fk_MetricaDesempeno_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Reporte" ADD CONSTRAINT "fk_Reporte_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Recompensa" ADD CONSTRAINT "fk_Recompensa_id_Usuario_Usuario" FOREIGN KEY ("id_Usuario") REFERENCES "Usuario" ("id_Usuario") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "ReglaTransito" ADD CONSTRAINT "fk_ReglaTransito_id_Escenario_Escenario" FOREIGN KEY ("id_Escenario") REFERENCES "Escenario" ("id_Escenario") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "EventoVial" ADD CONSTRAINT "fk_EventoVial_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
ALTER TABLE "Infraccion" ADD CONSTRAINT "fk_Infraccion_id_Simulacion_Simulacion" FOREIGN KEY ("id_Simulacion") REFERENCES "Simulacion" ("id_Simulacion") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE; 
